version: '3'
services:
  dns:
    container_name: "dnsmasq"
    image: 'jpillora/dnsmasq:latest'
    restart: always
    environment:
      HTTP_USER: "admin"
      HTTP_PASS: "123456"
    ports:
      - '53:53/udp'
      - '8080:8080'
    volumes:
      - 'F:\\docker\\docker-compose\\dns-nginx\\conf\\dns\\dnsmasq.conf:/etc/dnsmasq.conf'
      - 'F:\\docker\\docker-compose\\dns-nginx\\conf\\dns\\dnsmasqhosts:/etc/dnsmasqhosts'
      - 'F:\\docker\\docker-compose\\dns-nginx\\conf\\dns\\resolv.dnsmasq:/etc/resolv.dnsmasq'

  nginx:
    container_name: "nginx"
    image: "nginx:latest"
    ports:
      - '80:80'
    volumes:
      - 'F:\\docker\\docker-compose\\dns-nginx\\conf\\nginx\\conf.d:/etc/nginx/conf.d'
      - 'F:\\docker\\docker-compose\\dns-nginx\\conf\\nginx\\nginx.conf:/etc/nginx/nginx.conf'